/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.hamcrest.CoreMatchers;
import org.junit.Assert;
import org.junit.jupiter.api.Test;

public class AppTest {
    @Test
    public void testAppHasAGreeting() {
        App classUnderTest = new App();
        Assert.assertThat(classUnderTest, CoreMatchers.notNullValue());
    }
}
